filesenseai:
  cohere-api-key: ${COHERE_API_KEY:}
  aws-s3-bucket: ${AWS_S3_BUCKET:}
  aws-region: ${AWS_REGION:us-east-1}

spring:
  main:
    web-application-type: none
    log-startup-info: false

logging:
  level:
    root: WARN